# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         pvconv
version:      0.56
version_from: bin/pvconv.pl
installdirs:  site
requires:
    Getopt::ArgvFile:              1.06
    Math::Matrix:                  0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
